spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema/schema-postgresql.sql

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/batchdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver



logging:
  level:
    com.example.springbatchdemo: DEBUG
    org.springframework.batch: DEBUG
