spring:
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration
      - io.awspring.cloud.autoconfigure.core.AwsAutoConfiguration
      - io.awspring.cloud.autoconfigure.core.CredentialsProviderAutoConfiguration
      - io.awspring.cloud.autoconfigure.core.RegionProviderAutoConfiguration
      - io.awspring.cloud.autoconfigure.s3.S3TransferManagerAutoConfiguration

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/batchdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

app:
  s3:
    use-local-file: true
    local-file-path: sample-data/orders_sample.csv

logging:
  level:
    com.example.springbatchdemo: DEBUG
    org.springframework.batch: DEBUG
